In [2]:
import pandas as pd

In [ ]:
races_df=pd.read_csv("../data/raw/races.csv")
races_df

In [ ]:
results_df=pd.read_csv("../data/raw/results.csv")
results_df

In [ ]:
races_results=races_df.merge(results_df)

In [ ]:
races_results

In [ ]:
driver_standingsdf=pd.read_csv("../data/raw/driver_standings.csv")
drivers_df=pd.read_csv("../data/raw/driver_standings.csv")
driver_standings_df= driver_standingsdf.fillna(0)

In [ ]:
results= driver_standings_df.merge(drivers_df, how='left', on= 'driverId')
results_filtered = results[results['position'] == 1]

In [ ]:
circuits_df=pd.read_csv("../data/raw/circuits.csv")

In [ ]:
circuits_df["country"].unique()

In [ ]:
races_df=pd.read_csv("../data/raw/races.csv")
races_new=races_df['name'].str.split(' ',n=1,expand=True)
races_df['name'].unique()

In [ ]:
races_df['name'].replace(to_replace={'Australian' : 'Australia','Malaysian': 'Malaysia'})

In [ ]:
'Australia', 'Malaysia', 'Bahrain', 'Spain', 'Turkey', 'Monaco',
       'Canada', 'France', 'UK', 'Germany', 'Hungary', 'Belgium', 'Italy',
       'Singapore', 'Japan', 'China', 'Brazil', 'USA', 'Austria', 'UAE',
       'Argentina', 'Portugal', 'South Africa', 'Mexico', 'Korea',
       'Netherlands', 'Sweden', 'Morocco', 'Switzerland', 'India',
       'Russia', 'Azerbaijan', 'Vietnam']

In [87]:
constructors_df=pd.read_csv("../data/raw/constructors.csv")
consrtuctor_results_df=pd.read_csv("../data/raw/constructor_results.csv")
constructors_df

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
...,...,...,...,...,...
206,209,manor,Manor Marussia,British,http://en.wikipedia.org/wiki/Manor_Motorsport
207,210,haas,Haas F1 Team,American,http://en.wikipedia.org/wiki/Haas_F1_Team
208,211,racing_point,Racing Point,British,http://en.wikipedia.org/wiki/Racing_Point_F1_Team
209,212,alpha_tauri,Scuderia Alpha Tauri,Italian,http://en.wikipedia.org/wiki/Scuderia_Alpha_Tauri
210,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri

In [88]:
new_df=consrtuctor_results_df.merge(constructors_df,on='constructorId', how='left')

In [89]:
new_df.drop(columns=['status'],inplace=True)

In [90]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11680 entries, 0 to 11679
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   constructorResultsId  11680 non-null  int64
 1   raceId                11680 non-null  int64
 2   constructorId         11680 non-null  int64
 3   points                11680 non-null  float64
 4   constructorRef        11680 non-null  object
 5   name                  11680 non-null  object
 6   nationality           11680 non-null  object
 7   url                   11680 non-null  object
dtypes: float64(1), int64(3), object(4)
memory usage: 821.2+ KB

In [101]:
constructor_standings_df=pd.read_csv("../data/raw/constructor_standings.csv")
w=constructor_standings_df.loc[constructor_standings_df['wins']==1].count()
constructor_standings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12436 entries, 0 to 12435
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   constructorStandingsId  12436 non-null  int64
 1   raceId                  12436 non-null  int64
 2   constructorId           12436 non-null  int64
 3   points                  12436 non-null  float64
 4   position                12436 non-null  int64
 5   positionText            12436 non-null  object
 6   wins                    12436 non-null  int64
dtypes: float64(1), int64(5), object(1)
memory usage: 680.2+ KB

In [102]:
new_cons_df=constructor_standings_df.merge(new_df,on=['raceId','constructorId'], how='left')

In [103]:
new_cons_df

,constructorStandingsId,raceId,constructorId,points_x,position,positionText,wins,constructorResultsId,points_y,constructorRef,name,nationality,url
0,1,18,1,14.0,1,1,1,1.0,14.0,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,18,2,8.0,3,3,0,2.0,8.0,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,18,3,9.0,2,2,0,3.0,9.0,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,18,4,5.0,4,4,0,4.0,5.0,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,18,5,2.0,5,5,0,5.0,2.0,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12431,27608,1042,4,120.0,5,5,0,16176.0,6.0,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
12432,27609,1042,51,5.0,8,8,0,16177.0,0.0,alfa,Alfa Romeo,Italian,http://en.wikipedia.org/wiki/Alfa_Romeo_in_For...
12433,27610,1042,3,0.0,10,10,0,16178.0,0.0,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
12434,27611,1042,9,226.0,2,2,1,16171.0,15.0,red_bull,Red Bull,Austrian,http://en.wikipedia.org/wiki/Red_Bull_Racing
12435,27612,1042,210,3.0,9,9,0,16179.0,0.0,haas,Haas F1 Team,American,http://en.wikipedia.org/wiki/Haas_F1_Team

In [120]:
#look up the rows with win==1
cons_no1=new_cons_df.loc[new_cons_df['wins']==1]
cons_no1_new=cons_no1[['wins','name']]

In [121]:
#group the winners by their names and take the count of wins within each constructor
cons_gb=cons_no1_new.groupby(['name']).count()

In [123]:
cons_gb.sort_values(by=['wins'],ascending=False)

                 wins
name
Ferrari           189
McLaren           125
Williams          112
Brabham            70
BRM                60
Tyrrell            55
Red Bull           47
Renault            37
Benetton           37
Mercedes           29
Team Lotus         29
Ligier             29
Jordan             24
Lotus F1           22
March              19
Cooper-Climax      13
Cooper-Maserati    12
BMW Sauber         12
Lotus-Ford         11
Lotus-Climax       11
Honda              10
Hesketh             7
Eagle-Weslake       7
Shadow              6
McLaren-Ford        6
Brabham-Climax      6
Penske              6
Porsche             6
Toro Rosso          5
AlphaTauri          5
Wolf                5
Matra-Ford          4
Brabham-Repco       4
Stewart             3
Brabham-Ford        2
Lotus-BRM           2
Cooper              1
Brawn               1
Vanwall             1