In [1]:
import pandas as pd

In [3]:
drivers_df = pd.read_csv("drivers.csv")
laps_df = pd.read_csv("lap_times.csv")

In [43]:
Drivers_merge = drivers_df.merge(laps_df, left_on='driverId', right_on='driverId')
Drivers_merge

,driverId,driverRef,number,code,forename,surname,dob,nationality,url,raceId,lap,position,time,milliseconds
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,841,1,2,1:40.573,100573
1,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,841,2,2,1:33.774,93774
2,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,841,3,2,1:32.900,92900
3,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,841,4,2,1:32.582,92582
4,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,841,5,2,1:32.471,92471
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485105,849,latifi,6,LAT,Nicholas,Latifi,1995-06-29,Canadian,http://en.wikipedia.org/wiki/Nicholas_Latifi,1042,60,18,1:22.851,82851
485106,849,latifi,6,LAT,Nicholas,Latifi,1995-06-29,Canadian,http://en.wikipedia.org/wiki/Nicholas_Latifi,1042,61,18,1:22.552,82552
485107,849,latifi,6,LAT,Nicholas,Latifi,1995-06-29,Canadian,http://en.wikipedia.org/wiki/Nicholas_Latifi,1042,62,18,1:22.453,82453
485108,849,latifi,6,LAT,Nicholas,Latifi,1995-06-29,Canadian,http://en.wikipedia.org/wiki/Nicholas_Latifi,1042,63,18,1:23.571,83571
485109,849,latifi,6,LAT,Nicholas,Latifi,1995-06-29,Canadian,http://en.wikipedia.org/wiki/Nicholas_Latifi,1042,64,18,1:22.743,82743

In [9]:
constructors_df = pd.read_csv("constructors.csv")
constructors_df

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
...,...,...,...,...,...
206,209,manor,Manor Marussia,British,http://en.wikipedia.org/wiki/Manor_Motorsport
207,210,haas,Haas F1 Team,American,http://en.wikipedia.org/wiki/Haas_F1_Team
208,211,racing_point,Racing Point,British,http://en.wikipedia.org/wiki/Racing_Point_F1_Team
209,212,alpha_tauri,Scuderia Alpha Tauri,Italian,http://en.wikipedia.org/wiki/Scuderia_Alpha_Tauri
210,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri

In [16]:
constructors_standings = pd.read_csv("constructor_standings.csv")
constructors_standings

,constructorStandingsId,raceId,constructorId,points,position,positionText,wins
0,1,18,1,14.0,1,1,1
1,2,18,2,8.0,3,3,0
2,3,18,3,9.0,2,2,0
3,4,18,4,5.0,4,4,0
4,5,18,5,2.0,5,5,0
...,...,...,...,...,...,...,...
12431,27608,1042,4,120.0,5,5,0
12432,27609,1042,51,5.0,8,8,0
12433,27610,1042,3,0.0,10,10,0
12434,27611,1042,9,226.0,2,2,1
12435,27612,1042,210,3.0,9,9,0

In [28]:
Constructor_merge = constructors_df.merge(constructors_standings, left_on='constructorId', right_on='constructorId')
Constructor_merge

,constructorId,constructorRef,name,nationality,url,constructorStandingsId,raceId,points,position,positionText,wins
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,1,18,14.0,1,1,1
1,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,7,19,24.0,1,1,1
2,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,18,20,28.0,3,3,1
3,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,29,21,34.0,3,3,1
4,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,40,22,42.0,3,3,1
...,...,...,...,...,...,...,...,...,...,...,...
12431,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri,27557,1038,47.0,7,7,1
12432,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri,27567,1039,53.0,7,7,1
12433,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri,27587,1040,59.0,7,7,1
12434,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri,27597,1041,67.0,7,7,1
12435,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri,27607,1042,77.0,7,7,1

In [38]:
Races_df = pd.read_csv("races.csv")

In [39]:
Constructor_Final = Constructor_merge.merge(Races_df, left_on='raceId', right_on='raceId')
Constructor_Final.rename(columns={"name_x":"Constructor_Names","name_y":"Race_Name"},inplace=True)

In [40]:
Constructor_Final.drop(columns=["url_x","url_y"],inplace=True)

In [41]:
Constructor_Final

,constructorId,constructorRef,Constructor_Names,nationality,constructorStandingsId,raceId,points,position,positionText,wins,year,round,circuitId,Race_Name,date,time
0,1,mclaren,McLaren,British,1,18,14.0,1,1,1,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00
1,2,bmw_sauber,BMW Sauber,German,2,18,8.0,3,3,0,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00
2,3,williams,Williams,British,3,18,9.0,2,2,0,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00
3,4,renault,Renault,French,4,18,5.0,4,4,0,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00
4,5,toro_rosso,Toro Rosso,Italian,5,18,2.0,5,5,0,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12431,176,lotus-brm,Lotus-BRM,British,20741,679,0.0,7,7,0,1967,1,30,South African Grand Prix,1967-01-02,\N
12432,183,brabham-climax,Brabham-Climax,British,20739,679,2.0,5,5,0,1967,1,30,South African Grand Prix,1967-01-02,\N
12433,184,lds-climax,LDS-Climax,South African,20740,679,0.0,6,6,0,1967,1,30,South African Grand Prix,1967-01-02,\N
12434,189,eagle-climax,Eagle-Climax,American,20742,679,0.0,8,8,0,1967,1,30,South African Grand Prix,1967-01-02,\N
12435,191,brabham-repco,Brabham-Repco,British,20738,679,3.0,4,4,0,1967,1,30,South African Grand Prix,1967-01-02,\N

In [45]:
Drivers_merge = Drivers_merge.merge(constructors_standings, left_on='raceId', right_on='raceId')

In [46]:
Drivers_merge = Drivers_merge.merge(Races_df, left_on='raceId', right_on='raceId')

In [53]:
Drivers_merge.drop(columns=["url_x","url_y","time_x","time_y"])

,driverId,driverRef,number,code,forename,surname,dob,nationality,raceId,lap,...,constructorId,points,position_y,positionText,wins,year,round,circuitId,name,date
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,841,1,...,131,0.0,10,10,0,2011,1,1,Australian Grand Prix,2011-03-27
1,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,841,1,...,3,0.0,9,9,0,2011,1,1,Australian Grand Prix,2011-03-27
2,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,841,1,...,166,0.0,8,8,0,2011,1,1,Australian Grand Prix,2011-03-27
3,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,841,1,...,205,0.0,7,7,0,2011,1,1,Australian Grand Prix,2011-03-27
4,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,841,1,...,10,3.0,6,6,0,2011,1,1,Australian Grand Prix,2011-03-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5206802,40,friesacher,\N,FRI,Patrick,Friesacher,1980-09-26,Austrian,79,71,...,1,63.0,2,2,3,2005,9,19,United States Grand Prix,2005-06-19
5206803,40,friesacher,\N,FRI,Patrick,Friesacher,1980-09-26,Austrian,79,71,...,3,47.0,4,4,0,2005,9,19,United States Grand Prix,2005-06-19
5206804,40,friesacher,\N,FRI,Patrick,Friesacher,1980-09-26,Austrian,79,71,...,9,22.0,6,6,0,2005,9,19,United States Grand Prix,2005-06-19
5206805,40,friesacher,\N,FRI,Patrick,Friesacher,1980-09-26,Austrian,79,71,...,6,63.0,3,3,1,2005,9,19,United States Grand Prix,2005-06-19
5206806,40,friesacher,\N,FRI,Patrick,Friesacher,1980-09-26,Austrian,79,71,...,4,76.0,1,1,5,2005,9,19,United States Grand Prix,2005-06-19